/*
 * Generated installed-version snapshot.
 *
 * Imported by:
 * - src/appVersion/installedAppVersion.ts imports INSTALLED_APP_VERSION.
 *
 * Next file in UI flow:
 * - src/appVersion/installedAppVersion.ts reads this exported snapshot.
 *
 * No function calls:
 * - This generated file calls nothing. It only exports INSTALLED_APP_VERSION
 *   from line 27.
 *
 * Code flow:
 * 1. scripts/generate-app-build-version.js creates this file during Android
 *    and iOS builds.
 * 2. src/appVersion/installedAppVersion.ts imports this constant at app
 *    runtime and selects the current platform.
 * 3. src/drawer/SettingsScreen.tsx compares this installed version with the
 *    store version returned by src/api/appVersion.ts.
 *
 * Maintenance rule:
 * Do not edit this file directly. Change Android or iOS build version settings
 * instead, then run a normal build so this file is regenerated.
 */

export const INSTALLED_APP_VERSION = {
  "ios": {
    "versionName": "3.4.1",
    "buildNumber": "6",
    "versionCode": 6
  },
  "android": {
    "versionName": "3.4.1",
    "buildNumber": "77",
    "versionCode": 77
  }
} as const;
