/*
 * Generated installed-version snapshot.
 *
 * Imported by:
 * - src/appVersion/installedAppVersion.ts imports INSTALLED_APP_VERSION.
 *
 * Next file in UI flow:
 * - src/appVersion/installedAppVersion.ts reads this exported snapshot.
 *
 * No function calls:
 * - This generated file calls nothing. It only exports INSTALLED_APP_VERSION
 *   in the export statement below.
 *
 * Code flow:
 * 1. The platform version-setting scripts create this file before the release
 *    commit.
 * 2. src/appVersion/installedAppVersion.ts imports this constant at app
 *    runtime and selects the current platform.
 * 3. src/drawer/SettingsScreen.tsx compares this installed version with the
 *    store version returned by src/api/appVersion.ts.
 *
 * Release-preparation rule:
 * Do not edit this file directly. The iOS and Android version-setting scripts
 * regenerate it before the release commit. The iOS Archive and Android Bundle
 * packaging tasks do not modify it, so both store artifacts can be created
 * consecutively from one clean Git commit.
 */

export const INSTALLED_APP_VERSION = {
  "ios": {
    "versionName": "3.6.1",
    "buildNumber": "2",
    "versionCode": 2
  },
  "android": {
    "versionName": "3.6.1",
    "buildNumber": "83",
    "versionCode": 83
  }
} as const;
