import React, { useCallback, useEffect, useState } from 'react';
import { Alert, Linking, Platform, Pressable, Text, View } from 'react-native';
import {
  fetchStoreAppVersion,
  getUpdateCheckResult,
} from '../../api/appVersion';
import { getInstalledAppVersion } from '../../appVersion/installedAppVersion';
import type {
  InstalledAppVersion,
  UpdateCheckResult,
} from '../../types/appVersion/appVersionTypes';
import { settingsStyles } from '../../styles/drawer/settingsStyles';

const androidStoreUrl =
  'https://play.google.com/store/apps/details?id=com.codefest.movieapp';
const iosStoreUrl = 'https://apps.apple.com/us/app/movie-guider/id6465793035';

const initialUpdateCheck: UpdateCheckResult = {
  status: 'checking',
  storeVersion: null,
  message: 'Checking for updates...',
};

/*
 * Settings software-version section.
 *
 * UI flow:
 * 1. Reads the installed version generated by the native build.
 * 2. Reads the public store version from the Cloudflare app-version endpoint.
 * 3. Shows a small status summary and opens the correct store listing when
 *    the user taps the section title.
 */
export function SoftwareVersionSection() {
  const [installedVersion, setInstalledVersion] =
    useState<InstalledAppVersion | null>(null);
  const [updateCheck, setUpdateCheck] =
    useState<UpdateCheckResult>(initialUpdateCheck);
  const [isUpdateCheckLoading, setIsUpdateCheckLoading] = useState(true);
  const storeUrl = Platform.OS === 'android' ? androidStoreUrl : iosStoreUrl;
  const storeName =
    Platform.OS === 'android' ? 'Google Play Store' : 'Apple Store';
  const storeVersionLabel = `${storeName} Details`;
  const updateStatusLabel =
    updateCheck.status === 'updateAvailable'
      ? 'Update Available'
      : 'Current version installed';

  const loadVersionState = useCallback(async () => {
    setIsUpdateCheckLoading(true);

    try {
      const currentInstalledVersion = await getInstalledAppVersion();
      setInstalledVersion(currentInstalledVersion);

      const storeVersionResponse = await fetchStoreAppVersion();
      setUpdateCheck(
        getUpdateCheckResult(currentInstalledVersion, storeVersionResponse)
      );
    } catch (error) {
      console.error('Error checking app version:', error);
      setUpdateCheck({
        status: 'unavailable',
        storeVersion: null,
        message: 'Could not check for updates',
      });
    } finally {
      setIsUpdateCheckLoading(false);
    }
  }, []);

  useEffect(() => {
    loadVersionState();
  }, [loadVersionState]);

  async function handleCheckForUpdate() {
    await loadVersionState();

    try {
      await Linking.openURL(storeUrl);
    } catch (error) {
      console.error('Error opening app store URL:', error);
      Alert.alert(
        'Unable to Open Store',
        'The app store page could not be opened from this device.'
      );
    }
  }

  return (
    <View style={settingsStyles.settingBlock}>
      <Pressable
        onPress={handleCheckForUpdate}
        accessibilityRole="button"
        style={({ pressed }) => [pressed ? settingsStyles.pressed : null]}
      >
        <Text allowFontScaling={false} style={settingsStyles.linkText}>
          {storeVersionLabel}
        </Text>
      </Pressable>
      <Text allowFontScaling={false} style={settingsStyles.versionText}>
        Version: {formatInstalledVersion(installedVersion)}
      </Text>
      <Text
        allowFontScaling={false}
        style={[
          settingsStyles.updateStatusText,
          updateCheck.status === 'updateAvailable'
            ? settingsStyles.updateAvailableText
            : null,
        ]}
      >
        {isUpdateCheckLoading ? 'On Current Version' : updateStatusLabel}
      </Text>
      <Text allowFontScaling={false} style={settingsStyles.storeVersionText}>
        Tap above for version details
      </Text>
    </View>
  );
}

function formatInstalledVersion(version: InstalledAppVersion | null) {
  if (!version) {
    return 'Loading...';
  }

  if (Platform.OS === 'android' && version.versionCode !== null) {
    return `${version.versionName} (${version.versionCode})`;
  }

  if (version.buildNumber) {
    return `${version.versionName} (${version.buildNumber})`;
  }

  return version.versionName || 'Unknown';
}
