/**
 * Styles for MovieDetail information sections and provider links.
 *
 * Imported by:
 * - src/movie/components/MovieDetailInfoSections.tsx
 */
import { StyleSheet } from 'react-native';
import { colors } from '../colors';
import { scaleSize } from '../scale';

export const movieDetailInfoSectionStyles = StyleSheet.create({
  sectionLabel: {
    color: colors.textPrimary,
    fontSize: scaleSize(15),
    lineHeight: scaleSize(20),
    fontWeight: '700',
    letterSpacing: 0,
    marginTop: scaleSize(18),
    marginBottom: scaleSize(10),
    marginLeft: scaleSize(5),
  },
  infoPanel: {
    marginLeft: scaleSize(5),
    marginRight: scaleSize(5),
    padding: scaleSize(7),
    borderRadius: scaleSize(10),
    backgroundColor: colors.surfaceLight,
  },
  infoRow: {
    color: colors.textPrimary,
    fontSize: scaleSize(14),
    lineHeight: scaleSize(20),
    letterSpacing: 0,
    marginBottom: scaleSize(2),
  },
  infoLabel: {
    color: colors.textPrimary,
    fontWeight: '700',
  },
  watchProviderPanel: {
    marginLeft: scaleSize(5),
    marginRight: scaleSize(5),
    marginBottom: scaleSize(10),
    padding: scaleSize(7),
    borderRadius: scaleSize(10),
    backgroundColor: colors.surfaceLight,
  },
  watchProviderLabel: {
    color: colors.textPrimary,
    fontSize: scaleSize(14),
    lineHeight: scaleSize(20),
    letterSpacing: 0,
    marginBottom: scaleSize(2),
  },
  watchProviderRow: {
    minHeight: scaleSize(34),
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: scaleSize(7),
  },
  subscriptionGroup: {
    marginTop: scaleSize(14),
  },
  subscriptionGroupLabel: {
    color: colors.textPrimary,
    fontSize: scaleSize(14),
    lineHeight: scaleSize(20),
  },
  subscriptionGroupRows: {
    paddingLeft: scaleSize(10),
    borderLeftWidth: scaleSize(2),
    borderLeftColor: colors.borderSubtle,
    marginLeft: scaleSize(2),
  },
  watchProviderLogo: {
    width: scaleSize(30),
    height: scaleSize(30),
    borderRadius: scaleSize(5),
    backgroundColor: colors.surfaceWhite,
  },
  watchProviderName: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: scaleSize(14),
    lineHeight: scaleSize(20),
    letterSpacing: 0,
    marginLeft: scaleSize(10),
  },
  watchProviderUnavailable: {
    color: colors.textPrimary,
    fontSize: scaleSize(14),
    lineHeight: scaleSize(20),
    letterSpacing: 0,
  },
  providerOpenAction: {
    width: scaleSize(114),
    alignItems: 'center',
    marginHorizontal: scaleSize(6),
  },
  providerOpenButton: {
    height: scaleSize(24),
    paddingHorizontal: scaleSize(7),
    borderWidth: 1,
    borderColor: colors.searchAccent,
    borderRadius: 999,
    backgroundColor: colors.brandTintSurface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  providerOpenButtonDisabled: {
    borderColor: colors.borderDefault,
    backgroundColor: colors.surfaceMuted,
  },
  providerOpenIcon: {
    width: scaleSize(11),
    marginRight: scaleSize(4),
  },
  providerOpenLabel: {
    fontSize: scaleSize(11),
    lineHeight: scaleSize(14),
    fontWeight: '400',
    color: colors.brandText,
    textAlign: 'center',
  },
  providerOpenLabelDisabled: {
    color: colors.disabledText,
  },
  streamingMessage: {
    color: colors.textPrimary,
    fontSize: scaleSize(13),
    lineHeight: scaleSize(18),
    marginHorizontal: scaleSize(12),
    marginBottom: scaleSize(10),
  },
  companyRow: {
    minHeight: scaleSize(34),
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: scaleSize(10),
  },
  companyLogo: {
    width: scaleSize(30),
    height: scaleSize(30),
    borderRadius: scaleSize(5),
    backgroundColor: colors.surfaceWhite,
  },
  companyName: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: scaleSize(14),
    lineHeight: scaleSize(20),
    letterSpacing: 0,
    marginLeft: scaleSize(10),
  },
  productionCountriesPanel: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginLeft: scaleSize(5),
    marginRight: scaleSize(5),
    paddingVertical: scaleSize(7),
    paddingRight: scaleSize(10),
    borderRadius: scaleSize(10),
    backgroundColor: colors.surfaceLight,
  },
  productionCountry: {
    color: colors.textPrimary,
    fontSize: scaleSize(14),
    lineHeight: scaleSize(20),
    letterSpacing: 0,
    marginLeft: scaleSize(10),
  },
  footer: {
    alignItems: 'center',
    marginTop: scaleSize(40),
    marginBottom: scaleSize(50),
  },
  footerStrong: {
    color: colors.textPrimary,
    fontSize: scaleSize(14),
    lineHeight: scaleSize(20),
    fontWeight: '700',
    letterSpacing: 0,
  },
  footerText: {
    color: colors.textPrimary,
    fontSize: scaleSize(14),
    lineHeight: scaleSize(20),
    fontWeight: '400',
    letterSpacing: 0,
    marginTop: scaleSize(10),
  },
  footerLogoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceLight,
    paddingVertical: scaleSize(8),
    paddingHorizontal: scaleSize(11),
  },
  tmdbLogo: {
    width: scaleSize(41),
    height: scaleSize(30),
    transform: [{ scale: 1.1 }],
  },
  justWatchLogo: {
    width: scaleSize(41),
    height: scaleSize(41),
    marginLeft: scaleSize(26),
    transform: [{ scale: 1.1 }],
  },
  movieOfTheNightLink: {
    width: scaleSize(72),
    height: scaleSize(50),
    alignItems: 'center',
    justifyContent: 'space-between',
    marginLeft: scaleSize(26),
    transform: [{ scale: 1.1 }],
  },
  movieOfTheNightLogo: {
    width: scaleSize(36),
    height: scaleSize(36),
    borderRadius: scaleSize(4),
  },
  movieOfTheNightName: {
    color: colors.textPrimary,
    fontSize: scaleSize(7),
    lineHeight: scaleSize(11),
    fontWeight: '400',
    letterSpacing: 0,
    textAlign: 'center',
    includeFontPadding: false,
  },
  footerImdbLogo: {
    width: scaleSize(70),
    height: scaleSize(35),
    marginTop: scaleSize(10),
  },
});
